import test from './test.js'
import data from './orkn_event_reference.json' with { type: 'json' }

// takes the current filename `name.js` and imports `name.json`
// const fname = new URL(import.meta.url).pathname.split('/').pop()
// const { default: data } = await import(`./${fname}on`, {
//   with: { type: 'json' },
// })

const { play, restart, listen, expect, ingore, tap, wait, done } = test(data)

play()
expect('0 game load')
expect('0 room load')
expect('0 room 2 load')
expect('0 player load')
expect('0 sprite load')
expect('0 item load')
expect('0 sprite 2 load')
expect('0 item 2 load')
expect('0 game start')
expect('1 game enter')
expect('1 room enter')
expect('1 item at 10,5 enter')
expect('1 item at 14,5 enter')
expect('1 sprite at 12,6 enter')
expect('1 item at 10,8 enter')
expect('1 item at 14,8 enter')
expect('1 player enter')

// ignore()
await tap(BTN_UP)
expect('2 player update dx:0,dy:-1,tx:12,ty:8')
await tap(BTN_UP)
expect('3 player update dx:0,dy:-1,tx:12,ty:7')
await tap(BTN_RIGHT)
expect('4 player update dx:1,dy:0,tx:13,ty:7')
await tap(BTN_RIGHT)
expect('5 player update dx:1,dy:0,tx:14,ty:7')
await tap(BTN_RIGHT)
expect('6 player update dx:1,dy:0,tx:15,ty:7')
// listen()

await tap(BTN_RIGHT)
expect('7 player update dx:1,dy:0,tx:16,ty:7')
expect('7 game exit')
expect('7 room exit')
expect('7 item at 10,5 exit')
expect('7 item at 14,5 exit')
expect('7 sprite at 12,6 exit')
expect('7 item at 10,8 exit')
expect('7 item at 14,8 exit ')
expect('7 player exit')
await wait()
expect('8 game enter')
expect('8 room 2 enter')
expect('8 item 2 at 10,5 enter')
expect('8 item 2 at 12,5 enter')
expect('8 item 2 at 14,5 enter')
expect('8 sprite 2 at 12,7 enter')
expect('8 item 2 at 14,7 enter')
expect('8 item 2 at 10,9 enter')
expect('8 item 2 at 12,9 enter')
expect('8 item 2 at 14,9 enter')
expect('8 player enter')

await tap(BTN_RIGHT)
expect('9 player update dx:1,dy:0,tx:9,ty:7')
await tap(BTN_RIGHT)
expect('10 player update dx:1,dy:0,tx:10,ty:7')
await tap(BTN_DOWN)
expect('11 player update dx:0,dy:1,tx:10,ty:8')
await tap(BTN_DOWN)
expect('12 player update dx:0,dy:1,tx:10,ty:9')
expect('12 item 2 at 10,9 collect dx:0,dy:1,tx:10,ty:9')

await wait(5) // sayAdvanceDelay=0.2
await tap(BTN_A) // skip text
await tap(BTN_A) // close dialog

await tap(BTN_UP)
expect('20 player update dx:0,dy:-1,tx:10,ty:8')
await tap(BTN_UP)
expect('21 player update dx:0,dy:-1,tx:10,ty:7')
await tap(BTN_RIGHT)
expect('22 player update dx:1,dy:0,tx:11,ty:7')
await tap(BTN_RIGHT)
expect('23 player update dx:1,dy:0,tx:12,ty:7')
expect('23 sprite 2 at 12,7 interact dx:1,dy:0,tx:12,ty:7')
expect('23 game change option=Option 1')

await tap(BTN_B)
expect('24 game invalid')
await tap(BTN_A)
expect('25 game select option=Option 1')
expect('25 game change option=Option A')
await tap(BTN_RIGHT)
expect('26 game change option=Option C')
await tap(BTN_B)
expect('27 game dismiss')
await tap(BTN_A)
expect('28 game select option=Option 1')
expect('28 game change option=Option A')
await tap(BTN_A)
expect('29 game select option=Option A')

await tap(BTN_LEFT)
expect('30 player update dx:-1,dy:0,tx:10,ty:7')
await tap(BTN_LEFT)
expect('31 player update dx:-1,dy:0,tx:9,ty:7')
await tap(BTN_LEFT)
expect('32 player update dx:-1,dy:0,tx:8,ty:7')
expect('32 game exit')
expect('32 room 2 exit')
expect('32 item 2 at 10,5 exit')
expect('32 item 2 at 12,5 exit')
expect('32 item 2 at 14,5 exit')
expect('32 sprite 2 at 12,7 exit')
expect('32 item 2 at 14,7 exit')
expect('32 item 2 at 12,9 exit')
expect('32 item 2 at 14,9 exit')
expect('32 player exit')

await wait()
expect('33 game enter')
expect('33 room enter')
expect('33 item at 10,5 enter')
expect('33 item at 14,5 enter')
expect('33 sprite at 12,6 enter')
expect('33 item at 10,8 enter')
expect('33 item at 14,8 enter')
expect('33 player enter')

await tap(BTN_LEFT)
expect('34 player update dx:-1,dy:0,tx:15,ty:7')
await tap(BTN_LEFT)
expect('35 player update dx:-1,dy:0,tx:14,ty:7')
await tap(BTN_LEFT)
expect('36 player update dx:-1,dy:0,tx:13,ty:7')
await tap(BTN_LEFT)
expect('37 player update dx:-1,dy:0,tx:12,ty:7')
await tap(BTN_DOWN)
expect('38 player update dx:0,dy:1,tx:12,ty:8')
await tap(BTN_DOWN)
expect('39 player update dx:0,dy:1,tx:12,ty:9')
await tap(BTN_DOWN)
expect('40 player update dx:0,dy:1,tx:12,ty:10')

await tap(BTN_DOWN)
expect('41 player update dx:0,dy:1,tx:12,ty:11')
expect('41 game finish')

done()
