#!/usr/bin/env node

import { bundle } from '../assets/mjs/bundler.js'

const data = []
process.stdin.on('readable', () => {
  let chunk
  while (null !== (chunk = process.stdin.read())) {
    data.push(chunk)
  }
})

process.stdin.on('end', () => {
  process.stdout.write(
    bundle({
      gameData: JSON.parse(data.join('')),
    })
  )
})
