#!/usr/bin/env node

import { minify } from '../assets/mjs/minify.js'

const data = []
process.stdin.on('readable', () => {
  let chunk
  while (null !== (chunk = process.stdin.read())) {
    data.push(chunk)
  }
})

process.stdin.on('end', () => {
  process.stdout.write(minify(JSON.parse(data.join(''))))
})
