#!/usr/bin/env node

const cmd = process.argv[2]
if (cmd == 'minify') {
  import('./minify')
} else if (cmd == 'bundle') {
  import('./bundle')
} else {
  console.error(`Unknown command: ${cmd}`)
  process.exit(1)
}
